apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:fpm
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "nextcloud"
            - name: MYSQL_USER
              value: "nextcloud"
            - name: MYSQL_HOST
              value: "cloud-database"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html
      volumes:
        - name: app-storage
          emptyDir: {}
