apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: QnA4eVlyT3JiSmMwTmpJdml2MkdLY0NGdHlZVkZhZ29kSXg0bGpyQlQ1SnluOHUyTGxU
  MYSQL_PASSWORD: QnA4eVlyT3JiSmMwTmpJdml2MkdLY0NGdHlZVkZhZ29kSXg0bGpyQlQ1SnluOHUyTGxU

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/nextcloud/db/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-database
  template:
    metadata:
      labels:
        app: cloud-database
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          envFrom:
            - secretRef:
                name: db-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:fpm
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "nextcloud"
            - name: MYSQL_USER
              value: "nextcloud"
            - name: MYSQL_HOST
              value: "cloud-database"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html
      volumes:
        - name: app-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-app
spec:
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
